name = "Tensors"
uuid = "a57d67a0-4683-47ff-be60-6114e830558b"
authors = ["Sergio Sánchez Ramírez <sergio.sanchez.ramirez@bsc.es>"]
version = "0.1.0"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"

[compat]
ChainRulesCore = "1.15"
OMEinsum = "0.7"
julia = "1.8"
